package modelo;
// Generated 19 ene 2026, 8:30:00 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

import org.hibernate.Session;

import com.example.springBt.HibernateUtil;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Horarios generated by hbm2java
 */

public class Horarios implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Users users;
	private Modulos modulos;
	private String dia;
	private byte hora;
	private String aula;
	private String observaciones;
	private Timestamp createdAt;
	private Timestamp updatedAt;
	private String nombreModulo;

	public Horarios() {
	}

	public Horarios(modelo.Horarios h) {
		this.dia = h.getDia();
		this.hora = h.getHora();
		this.aula = h.getAula();
		this.observaciones = h.getObservaciones();
		if (h.getUsers() != null) {
			this.users = new Users(h.getUsers());
		}
		this.modulos = new Modulos(h.getModulos());
		this.nombreModulo = (h.getModulos() != null) ? h.getModulos().getNombre() : null;
		this.createdAt = h.getCreatedAt();
		this.updatedAt = h.getUpdatedAt();

	}

	public Horarios(Users users, Modulos modulos, String dia, byte hora) {
		this.users = users;
		this.modulos = modulos;
		this.dia = dia;
		this.hora = hora;
	}

	public Horarios(Users users, Modulos modulos, String dia, byte hora, String aula, String observaciones,
			Timestamp createdAt, Timestamp updatedAt) {
		this.users = users;
		this.modulos = modulos;
		this.dia = dia;
		this.hora = hora;
		this.aula = aula;
		this.observaciones = observaciones;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;

	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@JsonIgnore
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@JsonIgnore
	public Modulos getModulos() {
		return this.modulos;
	}

	public void setModulos(Modulos modulos) {
		this.modulos = modulos;
	}

	public String getDia() {
		return this.dia;
	}

	public void setDia(String dia) {
		this.dia = dia;
	}

	public byte getHora() {
		return this.hora;
	}

	public void setHora(byte hora) {
		this.hora = hora;
	}

	public String getAula() {
		return this.aula;
	}

	public void setAula(String aula) {
		this.aula = aula;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

	public String getNombreModulo() {
		return nombreModulo;
	}

	public void setNombreModulo(String nombreModulo) {
		this.nombreModulo = nombreModulo;
	}

	@JsonIgnore
	public static List<Horarios> obtenerHorarioProfesor(Integer idProfesor) {
		List<Horarios> resultado = new ArrayList<>();
		try (Session session = HibernateUtil.getSessionFactory().openSession()) {
			final Users profesor = session.get(Users.class, idProfesor);
			resultado = session.createQuery("SELECT h FROM Horarios h WHERE h.users = :profesor ORDER BY h.dia, h.hora",
					Horarios.class).setParameter("profesor", profesor).getResultList();
			resultado.replaceAll(h -> new Horarios(h));
		}
		return resultado;
	}

	@JsonIgnore
	public static List<Horarios> obtenerTodosHorarios() {
		List<Horarios> resultado = new ArrayList<>();
		try (Session session = HibernateUtil.getSessionFactory().openSession()) {
			resultado = session.createQuery("SELECT h FROM Horarios h ORDER BY h.dia, h.hora", Horarios.class).getResultList();
			resultado.replaceAll(h -> new Horarios(h));
		}
		return resultado;
	}

	@JsonIgnore
	public static List<Horarios> obtenerHorarioAlumno(Integer idAlumno) {
		List<Horarios> resultado = new ArrayList<>();
		try (Session session = HibernateUtil.getSessionFactory().openSession()) {
			Users alumno = session.get(Users.class, idAlumno);
			resultado = session.createQuery(
				"SELECT h FROM Horarios h " +
				"JOIN h.modulos m " +
				"JOIN m.ciclos c " +
				"JOIN Matriculaciones mat ON mat.ciclos = c " +
				"WHERE mat.users = :Alumno " +
				"ORDER BY h.dia, h.hora",
				Horarios.class
			).setParameter("Alumno", alumno).getResultList();
			resultado.replaceAll(h -> new Horarios(h));
		}
		return resultado;
	}

	@JsonIgnore
	public static int obtenerTipoUsuario(int idUsuario) {
        try (Session session = HibernateUtil.getSessionFactory().openSession()) {
            Users user = session.get(Users.class, idUsuario);
            if (user != null && user.getTipos() != null && user.getTipos().getId() != null) {
                return user.getTipos().getId();
            }
        }
        return -1; // tipo desconocido
    }

}
